### ISSUE TITLE
Github actions breaking

### ISSUE THREAD

**Issue by muzammilosman** [frabert/replace-string-action#3]
Using this action for time formatting, threw the following error while executing the step

```sh
Run frabert/replace-string-action@master
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '@actions/core'
Require stack:
- /home/runner/work/_actions/frabert/replace-string-action/master/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by frabert** [comment]
Should be fixed with the last commit. Sorry for the inconvenience.

**Comment by muzammilosman** [comment]
Thank you. Working fine now
